/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.application.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.application.Controller.BookingController;
import lk.ijse.application.Controller.PaymentController;
import lk.ijse.application.modal.BookingDetails;
import lk.ijse.application.modal.PaymentDet;

/**
 *
 * @author Mora
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    Payment(String bbid) {
        initComponents();
        bid.setText(bbid);
        try {
            LoadAllData(bbid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        perday = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        kms = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        perkm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Carno = new javax.swing.JLabel();
        bid = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        outdate = new javax.swing.JLabel();
        advance = new javax.swing.JLabel();
        daycharge = new javax.swing.JLabel();
        kmcharge = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        indate = new javax.swing.JLabel();
        chargefull = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        freekm = new javax.swing.JTextField();
        freelable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Per Km");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BOOKING ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("OUT_DATE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NIC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        perday.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        perday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdayActionPerformed(evt);
            }
        });
        jPanel1.add(perday, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 70, 30));

        days.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, 30));

        kms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(kms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Full Payment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Km");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 60, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Free Km");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Per Day");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("CAR_NO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Advance");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 130, -1));

        perkm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        perkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkmActionPerformed(evt);
            }
        });
        jPanel1.add(perkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 70, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 100, 40));

        Carno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Carno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 280, 30));

        bid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 290, 30));

        nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 290, 30));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 290, 30));

        outdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(outdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 290, 30));

        advance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advance.setText("0");
        jPanel1.add(advance, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 90, 30));

        daycharge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        daycharge.setText("Rs");
        jPanel1.add(daycharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, 30));

        kmcharge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kmcharge.setText("Rs");
        jPanel1.add(kmcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("IN_DATE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        indate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(indate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 290, 30));

        chargefull.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chargefull.setText("Rs");
        jPanel1.add(chargefull, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 80, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("-");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 20, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Days");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, -1));

        freekm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        freekm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freekmActionPerformed(evt);
            }
        });
        jPanel1.add(freekm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 70, 30));

        freelable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(freelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void perdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdayActionPerformed
         try{
        
        int day = Integer.parseInt(days.getText());
        int howday = Integer.parseInt(perday.getText());
        
        int Dcharge = day*howday;
        String changeintDay = String.valueOf(Dcharge);
        daycharge.setText(changeintDay);
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Enter Payment");
       }
    }//GEN-LAST:event_perdayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
        
        int total =Integer.parseInt(daycharge.getText());
        int total1= Integer.parseInt(kmcharge.getText());
        int adv = Integer.parseInt(advance.getText());
        
        
        int full = total+total1-adv;
        String fullamout = String.valueOf(full);
        chargefull.setText(fullamout);
        
        
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Enter Payment");
       }
        
      
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void perkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkmActionPerformed
          try{
        
        int km = Integer.parseInt(kms.getText());
        int howkm = Integer.parseInt(perkm.getText());
        
        int free = Integer.parseInt(freekm.getText().trim());
        int Dcharge = km*howkm;
        String changeintkm = String.valueOf(Dcharge);
        kmcharge.setText(changeintkm); 
             

       
       }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Enter Payment");
       }
    }//GEN-LAST:event_perkmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String id = bid.getText();
       String nic = this.nic.getText();
       String name = this.name.getText();
       String outdate = this.outdate.getText();
       String indate = this.indate.getText();
       String kmc = kmcharge.getText() ;
       String dch = daycharge.getText();
       String ad = advance.getText();
       String full = chargefull.getText();
       String carno = Carno.getText();
       String kmrs = kms.getText();
       String dayrs = days.getText();
       String free = freekm.getText();
       
       PaymentDet p1= new PaymentDet(id, nic, name, outdate, indate,kmrs, kmc, dayrs,dch, ad, full,carno,free);
       
        try {
            if(new PaymentController().SavePayment(p1)){
            JOptionPane.showMessageDialog(null, "Paid");
            
            dispose();
            new Print(id,name,full,indate).setVisible(true);
        }else{
                JOptionPane.showMessageDialog(null, "Try again");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void freekmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freekmActionPerformed
        String text = freekm.getText();
        freelable.setText(text+" Km");
    }//GEN-LAST:event_freekmActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carno;
    private javax.swing.JLabel advance;
    private javax.swing.JLabel bid;
    private javax.swing.JLabel chargefull;
    private javax.swing.JLabel daycharge;
    private javax.swing.JTextField days;
    private javax.swing.JTextField freekm;
    private javax.swing.JLabel freelable;
    private javax.swing.JLabel indate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kmcharge;
    private javax.swing.JTextField kms;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nic;
    private javax.swing.JLabel outdate;
    private javax.swing.JTextField perday;
    private javax.swing.JTextField perkm;
    // End of variables declaration//GEN-END:variables

    private void LoadAllData(String bbid) throws ClassNotFoundException, SQLException {
        try {
            BookingDetails paymentDetail = new BookingController().getPaymentDetail(bbid);
            nic.setText(paymentDetail.getNIC());
            name.setText(paymentDetail.getFullname());
            outdate.setText(paymentDetail.getDate());
            advance.setText(paymentDetail.getAdvance());
            Carno.setText(paymentDetail.getCarNumber());
            SimpleDateFormat sdf= new SimpleDateFormat("YYYY/MM/dd HH:mm:ss");
            Date date1= new Date();
           indate.setText(sdf.format(date1));
            
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
